scanner:
  timeout: 30
  threads: 100
  retry: 3

ports:
  default_range: "1-1000"
  common_ports: [21,22,23,25,53,80,110,135,139,143,443,445,465,587,993,995,1433,1521,3306,3389,5432,5900,6379,8080,8443]

fingerprint:
  signatures_path: "configs/signatures"
  timeout: 5

vulnscan:
  templates_path: "configs/templates"
  concurrent: 10
  timeout: 30

logging:
  level: "info"
  file: "logs/scanner.log"
  format: "json" 